### ISSUE TITLE
xgboost tidiers

### ISSUE THREAD

**Issue by jwilber** [njtierney/broomstick#11]
Hey Nicholas,

I'd like to add some tidiers for `xgboost` sometime this month - is this still under active development/the correct place to submit a PR?
 If so, how's that sound? 
Thanks!

**Comment by njtierney** [comment]
Hello!

Sorry I didn't see this, I was in conference mode.

I'd definitely welcome a PR for tidying xgboost output :)

**Comment by njtierney** [comment]
Hi @jwilber - just wondering if you are still interested in this?

**Comment by jwilber** [comment]
Hey, I haven't touched R for a fair amount of time so probably not!

**Comment by njtierney** [comment]
OK! Thanks for your initial offer, have a good one :)
