### ISSUE TITLE
finish augment for rpart

### ISSUE THREAD

**Issue by njtierney** [njtierney/broomstick#14]

**Comment by talgalili** [comment]
Thanks Njtierney/Broomstick for the diffs.

**Comment by njtierney** [comment]
Thanks! What do you mean by "the diffs" ?

**Comment by talgalili** [comment]
Oops, I saw this via email and thought this was a pull request not an
issue. Well, but thanks for you involvement then :)

**Comment by njtierney** [comment]
No worries, glad you like the package!
