### ISSUE TITLE
tightening integration with tidymodels machinery

### ISSUE THREAD

**Issue by simonpcouch** [njtierney/broomstick#21]
Hi there @njtierney! My coworker Hannah Frick said she had chatted with you about this package recently and you said you thought it might be time for some updates.

Would you be open to a few PRs to integrate this package and its machinery more closely with broom, [bonsai](https://github.com/tidymodels/bonsai), and [modeltests](https://github.com/alexpghayes/modeltests)? What are your thoughts on releasing this package to CRAN?

Happy to put in some effort here and can file a few issues to get discussion started on what I have in mind specifically, if you're up for it! No pressure from me if you're not looking to develop this package further / in this direction. :)

**Comment by njtierney** [comment]
Hi @simonpcouch !

I would very much be open to some PRs! That would be excellent. Happy to review things, contribute to discussion and get things moving on this package, I haven't had the need to use it for a while so I haven't quite had the motivation to implement a lot of the features it needs to be fully fledged. But I'd love to get back into it, and would very much welcome interaction :)

**Comment by simonpcouch** [comment]
Great to hear, @njtierney! 

It seems I've struggled to bring this to the top of my to-do list as well since filing this issue.🙈 Happy to know that you'd welcome contributions, and I'll drop in a PR here-or-there as I come across use cases for this package myself. :)

**Comment by njtierney** [comment]
OK sounds great, thanks so much, @simonpcouch  :)
